# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/Documents/tuas/camera-things

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/Documents/tuas/camera-things

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documents/tuas/camera-things/CMakeFiles /home/daniel/Documents/tuas/camera-things//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documents/tuas/camera-things/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raspy

# Build rule for target.
raspy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raspy
.PHONY : raspy

# fast build rule for target.
raspy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/build
.PHONY : raspy/fast

event_loop.o: event_loop.cpp.o
.PHONY : event_loop.o

# target to build an object file
event_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/event_loop.cpp.o
.PHONY : event_loop.cpp.o

event_loop.i: event_loop.cpp.i
.PHONY : event_loop.i

# target to preprocess a source file
event_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/event_loop.cpp.i
.PHONY : event_loop.cpp.i

event_loop.s: event_loop.cpp.s
.PHONY : event_loop.s

# target to generate assembly for a file
event_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/event_loop.cpp.s
.PHONY : event_loop.cpp.s

raspy.o: raspy.cpp.o
.PHONY : raspy.o

# target to build an object file
raspy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/raspy.cpp.o
.PHONY : raspy.cpp.o

raspy.i: raspy.cpp.i
.PHONY : raspy.i

# target to preprocess a source file
raspy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/raspy.cpp.i
.PHONY : raspy.cpp.i

raspy.s: raspy.cpp.s
.PHONY : raspy.s

# target to generate assembly for a file
raspy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/raspy.cpp.s
.PHONY : raspy.cpp.s

simple-cam.o: simple-cam.cpp.o
.PHONY : simple-cam.o

# target to build an object file
simple-cam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/simple-cam.cpp.o
.PHONY : simple-cam.cpp.o

simple-cam.i: simple-cam.cpp.i
.PHONY : simple-cam.i

# target to preprocess a source file
simple-cam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/simple-cam.cpp.i
.PHONY : simple-cam.cpp.i

simple-cam.s: simple-cam.cpp.s
.PHONY : simple-cam.s

# target to generate assembly for a file
simple-cam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raspy.dir/build.make CMakeFiles/raspy.dir/simple-cam.cpp.s
.PHONY : simple-cam.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raspy"
	@echo "... event_loop.o"
	@echo "... event_loop.i"
	@echo "... event_loop.s"
	@echo "... raspy.o"
	@echo "... raspy.i"
	@echo "... raspy.s"
	@echo "... simple-cam.o"
	@echo "... simple-cam.i"
	@echo "... simple-cam.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

