name: Build Camera

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build in Container
      run: |
        docker run --rm --platform linux/arm64 \
        -v ${{ github.workspace }}:/workspace \
        -w /workspace \
        dtcooper/raspberrypi-os:bookworm \ # I had to use this b/c of pi-specific dependencies 
        /bin/bash -c " \
            apt-get update && \
            apt-get install -y \
                build-essential \
                cmake \
                pkg-config \
                libcamera-dev \
                libevent-dev \
                libusb-1.0-0-dev \
                git && \
            git config --global --add safe.directory /workspace && \
            mkdir -p build && \
            cd build && \
            cmake .. && \
            make -j\$(nproc) \
        "
